"""Add moderation, premium, and retention fields

Revision ID: 8adff25aacfa
Revises: 5c98c22459c0
Create Date: 2026-08-13 10:54:48.091399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adff25aacfa'
down_revision = '5c98c22459c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium')
        batch_op.drop_column('banned_at')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('ended_at')
        batch_op.drop_column('call_started_at')

    # ### end Alembic commands ###
